# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# route_finder.py
# Created on: 2015-03-03 12:36:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("Network")


# Local variables:
van_roadsND = "van_roadsND"
van_grocery = "van_grocery"
dauid = "dauid"
van_grocery_routes = "van_grocery_routes"
van_grocery_routes__2_ = "van_grocery_routes"
van_grocery_routes__3_ = "van_grocery_routes"

# Process: Make Closest Facility Layer
arcpy.MakeClosestFacilityLayer_na(van_roadsND, "van_grocery_routes", "Length", "TRAVEL_TO", "", "1", "", "ALLOW_UTURNS", "", "NO_HIERARCHY", "", "TRUE_LINES_WITH_MEASURES", "", "NOT_USED")

# Process: Add Locations
arcpy.AddLocations_na(van_grocery_routes, "Facilities", van_grocery, "Name Name #", "5000 Meters", "", "public_streets SHAPE;van_roadsND_Junctions NONE", "MATCH_TO_CLOSEST", "APPEND", "NO_SNAP", "5 Meters", "INCLUDE", "public_streets #;van_roadsND_Junctions #")

# Process: Add Locations (2)
arcpy.AddLocations_na(van_grocery_routes__2_, "Incidents", dauid, "", "5000 Meters", "", "public_streets SHAPE;van_roadsND_Junctions NONE", "MATCH_TO_CLOSEST", "APPEND", "NO_SNAP", "5 Meters", "INCLUDE", "public_streets #;van_roadsND_Junctions #")

# Process: Solve
arcpy.Solve_na(van_grocery_routes__3_, "SKIP", "TERMINATE", "")

