# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# project.py
# Created on: 2015-03-02 23:36:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
census_tracts = "census_tracts"
dauid = "C:\\Users\\carl\\Desktop\\webapp\\vancouver_features\\dauid.shp"

# Process: Feature To Point
arcpy.FeatureToPoint_management(census_tracts, dauid, "CENTROID")